services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://inventory-api:5000
      - AUTH_API_URL=http://auth-api:5000
