apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-frontend
  labels:
    app: tcc-frontend
spec:
  replicas: 1 # You can adjust the number of replicas for high availability
  selector:
    matchLabels:
      app: tcc-frontend
  template:
    metadata:
      labels:
        app: tcc-frontend
    spec:
      containers:
        - name: tcc-frontend
          image: us-central1-docker.pkg.dev/key-hope-455618-p3/tcc-erp-repo/frontend:latest
          ports:
            - containerPort: 4000
          env:
            # These environment variables would be used if you configure your Angular app
            # to read them, for example, using a custom webpack config or a script
            # that replaces placeholders in environment.prod.ts.
            # However, for API communication, directly pointing to K8s service names is better.
            - name: API_URL
              value: "http://inventory-service:5000/api/inventory" # Internal K8s service name
            - name: AUTH_API_URL
              value: "http://auth-service:5000/api/auth" # Internal K8s service name